version: 0.0
os: linux
files:
  - source: .
    destination: /var/www/vhosts/fantasylab.io
hooks:
  BeforeInstall:
    - location: deploy/before_install
      timeout: 300
      runas: root
  AfterInstall:
    - location: deploy/after_install
      timeout: 300
      runas: root